name: Trigger auto deployment for python-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-container-app-AutoDeployTrigger-ea47bb72-b337-4870-ac9e-152a34cde390.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYTHONCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: pythoncontaineryulong.azurecr.io
          registryUsername: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: python-container-app
          resourceGroup: pythoncontainer-rg
          imageToBuild: pythoncontaineryulong.azurecr.io/python-container-app:${{ github.sha }}
          

     

